### PR TITLE
Automated testing

### PR DESCRIPTION
**Pull request by patham9**
- includes testing for ./metta files in ./extend

### CODE REVIEW

**Comment by Necr0x0Der** [comment]
It is more related to #17 , but I'd propose to have a clean folder for the library/extension itself, i.e. without files which are not needed to the library itself. Thus, I'd move `example*` and `test.py` outside `extend`.

**Comment by patham9** [comment]
I agree, hm how about ./extend/tests as it would separate it from the different kind of tests in the project root?

**Comment by Necr0x0Der** [comment]
I suppose that we will have automatic library/extension installation for MeTTa, which will suppose a certain structure for libraries. Like in Python, everything in the folder can possibly become a part of the library. In the nearest future, I suppose that the folder name with the library code should have the name of the library (e.g., `mettamorph`) with something like `__init__.metta` (or whatever else Luke will propose), but since it is not supported yet, I'm not proposing to rename `extend`. However, I'd put these tests into `tests/extend` rather than `extend/tests`.

**Comment by patham9** [comment]
Sounds good, I will put them into tests/extend as you mentioned.

**Comment by Necr0x0Der** [comment]
> Sounds good, I will put them into `tests/extend` as you mentioned.

Will you do it within this PR?

**Comment by patham9** [comment]
I guess we can do it in a separate PR which could also address aspects of https://github.com/trueagi-io/metta-morph/issues/17
If that is fine then you can probably merge it already.

**Pull request merged**
